import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Contact, { fadeinUp } from "../components/Contact";
import LandingTitle from "../components/LandingTitle";
import { motion } from "framer-motion";
import { FaTiktok } from "react-icons/fa";
import { AiOutlineInstagram } from "react-icons/ai";
import { Canvas } from "@react-three/fiber";

const socials = [
  {
    href: "https://www.tiktok.com/@voidreincarnation",
    icon: <FaTiktok className='social-icons' />
  },
  {
    href: "https://www.instagram.com/voidreincarnation/",
    icon: <AiOutlineInstagram className='social-icons' />
  }
];

const circleVars = {
  hidden: {
    pathLength: 0,
    opacity: 0
  },
  show: {
    pathLength: 1,
    opacity: 1,
    transition: {
      pathLength: {
        duration: 0.6
      },
      opacity: {
        duration: 0.6
      }
    }
  }
};

//name
//interact
//questions
//gotoshop

//layout orgraphthigc cam
// make logo eye blink faster as you scroll until black washes over screen from bottom,
// then banner announcing next drop shows up and other stuff //layout orgpothpirc cam

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>VØID</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section className='px-8 min-h-screen flex items-center justify-center'>
        <div className='grid grid-cols-2 items-center'>
          <div style={{ width: "100%", height: "100%" }}>
            <LandingTitle />
          </div>
          <h1>VØID REINCARNATION</h1>
        </div>
      </section>

      <section className='px-8'>
        <section className='grid grid-cols-2 min-h-screen'>
          <div className='mt-[15vh]'>KAKWAKAWAKKWAKWKAWKKAW</div>
        </section>
        <section className='mt-[25vh] text-center'>
          <motion.h2 className='text-red-accent font-bold text-2xl'>
            こんにちは
          </motion.h2>
          <motion.p transition={fadeinUp}>
            Every piece goes through a journey made by hand. No piece of your
            clothing will have rivaled care — <br />
            unless it is made by VOID.
          </motion.p>
        </section>
      </section>

      <footer className='px-8 min-h-screen'>
        <div className='fixed left-8 top-2/3'>
          <motion.div
            initial={{ height: 0 }}
            animate={{ height: "125%" }}
            transition={{ ...fadeinUp, delay: 0.4 }}
            className='w-px absolute bg-red-accent -right-4 top-1/2 -translate-y-1/2'
          />
          <motion.ul
            variants={{
              show: { transition: { staggerChildren: 0.2, delayChildren: 1 } }
            }}
            initial='hidden'
            animate='show'
            className='flex flex-col gap-4'
          >
            {socials.map((social) => (
              <motion.li
                key={social.href}
                variants={{
                  hidden: { opacity: 0, y: 50 },
                  show: { opacity: 1, y: 0 }
                }}
                transition={fadeinUp}
              >
                <a href={social.href} className='z-50' target='_blank'>
                  <motion.div
                    initial='hidden'
                    whileHover='show'
                    className='relative rounded-full w-fit aspect-square isolate'
                  >
                    <svg
                      className='absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 -z-10'
                      width={50}
                      height={50}
                      xmlns='http://www.w3.org/2000/svg'
                      version='1.1'
                    >
                      <motion.circle
                        variants={circleVars}
                        cy={25}
                        cx={25}
                        r='20'
                        stroke='red'
                        strokeWidth='2'
                      />
                    </svg>
                    {social.icon}
                  </motion.div>
                </a>
              </motion.li>
            ))}
          </motion.ul>
        </div>
        <Contact />
      </footer>
    </>
  );
};

export default Home;
