import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Contact from "../components/Contact";
import LandingTitle from "../components/LandingTitle";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>VØID</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header></header>

      <main className='px-8'>
        <section className='grid grid-cols-2 min-h-screen'>
          <div className='mt-[15vh]'>
            suck my dick bitch
            {/* <Image
              src={"/blink.gif"}
              width={400}
              height={400}
              objectFit={"cover"}
            /> */}
          </div>
          {/* <LandingTitle /> */}
        </section>
      </main>

      <footer className='px-8'>
        <Contact />
        <motion.div className='relative'>
          <motion.div className='' />
        </motion.div>
      </footer>
    </>
  );
};

export default Home;
